@if(!$hasTeamGenerated)
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">{{ date('Y') }} - Week {{ date('W') }}</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <div class="box-body with-border">
            <div class="media discussion-widget-block">
                <div class="media-body">
                    @foreach($players as $key => $play)
                        @if($play->active)
                            @if($play->orderList == 1)
                                <p class="text-primary">{{ $play->title }}</p>
                            @endif
                            <p class="text-muted">
                                <small>&nbsp<i class="fa fa-circle text-{{ $play->title_icon }}"></i>&nbsp
                                    {{ $play->orderList }}.
                                    {{ $play->user->username }}
                                    ({{ $play->user->name }})
                                    {!! ($play->unavailable_for) ? ' - <span class="label label-danger label-outline" style="border-radius: 1em !important; color: #f96868 !important; background-color: transparent !important; padding-bottom: 1px !important;">' . $play->unavailable_for . '</span>' : '' !!}
                                </small>
                            </p>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@else
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Teams</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body with-border">
            <div class="row" style="padding: 0 10px">
            <div class="col-xs-6" style="text-align: left; border-right: #00a65a solid 1px;">
                <?php $greenSkill = 0; $redSkill = 0; ?>
                @foreach($players as $team_player)
                    <p style="margin: 0">
                        @if($team_player['current_team'] == 'green')
                            <?php $greenSkill += $team_player['skill_level']; ?>
                            <label style="margin-top: 5px; padding: 0 3px" class="label label-success label-round">{{ $team_player['skill_level'] }}</label>
                            ({{ substr($team_player['player_position'], 0, 1) }})
                            <span class="pull-right" style="padding: 0;">
                                {{ $team_player['user']['username'] }}
                            </span>

                        @endif
                    </p>
                @endforeach
                <label style="margin-top: 5px; padding: 0 3px" class="label label-success label-round label-outline pull-right">{{ $greenSkill }}</label>
            </div>

            <div class="col-xs-6" style="text-align: right; border-left: #9c1014 solid 1px;">
                @foreach($players as $team_player)
                    <p style="margin: 0">
                        @if($team_player['current_team'] == 'red')
                            <?php $redSkill += $team_player['skill_level']; ?>
                        <span class="pull-left" style="padding: 0;">
                            {{ $team_player['user']['username'] }}
                        </span>
                                ({{ substr($team_player['player_position'], 0, 1) }})
                                <label style="margin-top: 5px; padding: 0 3px" class="label label-danger label-round">{{ $team_player['skill_level'] }}</label>

                        @endif
                    </p>
                @endforeach
                <label style="margin-top: 5px; padding: 0 3px" class="label label-danger label-round label-outline pull-left">{{ $redSkill }}</label>

            </div>
            </div>
        </div>
        <div class="box-footer clearfix">
            Generated by
            {{ $generatedBy }} at {{ $generatedAt }}

        </div>
    </div>
@endif



